name: Deploy Easy Spaces to Power Platform

on:
  # Trigger on manual dispatch
  workflow_dispatch:
  
  # Trigger on push to main branch
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Build C# Plugins
      run: |
        cd plugins
        chmod +x build-plugins.sh
        ./build-plugins.sh
        
    - name: Verify Solution Package
      run: |
        echo "Using comprehensive solution: EasySpacesComprehensive_20250904_222252.zip"
        ls -la out/EasySpacesComprehensive_20250904_222252.zip
        unzip -l out/EasySpacesComprehensive_20250904_222146.zip
      
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1.9.1
        
    - name: Wait for any existing imports
      run: |
        echo "Waiting 2 minutes for any existing imports to complete..."
        sleep 120
        
    - name: Import Solution from Repository
      uses: microsoft/powerplatform-actions/import-solution@v1.9.1
      continue-on-error: true
      with:
        environment-url: 'https://org7cfbe420.crm.dynamics.com'
        app-id: ${{ secrets.POWERPLATFORM_APP_ID }}
        client-secret: ${{ secrets.POWERPLATFORM_CLIENT_SECRET }}
        tenant-id: ${{ secrets.POWERPLATFORM_TENANT_ID }}
        solution-file: 'out/EasySpacesComprehensive_20250904_222252.zip'
        force-overwrite: true
        publish-changes: true
        activate-plugins: true
        max-async-wait-time: 180
        
    - name: Deploy Plugins Separately
      continue-on-error: true
      run: |
        echo "Registering plugin assemblies..."
        pac plugin push \
          --path plugins/ReservationManager/bin/Release/net462/EasySpaces.ReservationManager.dll \
          --environment https://org7cfbe420.crm.dynamics.com || echo "Plugin registration failed - use manual method"
        pac plugin push \
          --path plugins/CustomerServices/bin/Release/net462/EasySpaces.CustomerServices.dll \
          --environment https://org7cfbe420.crm.dynamics.com || echo "Plugin registration failed - use manual method"  
        pac plugin push \
          --path plugins/MarketServices/bin/Release/net462/EasySpaces.MarketServices.dll \
          --environment https://org7cfbe420.crm.dynamics.com || echo "Plugin registration failed - use manual method"
        
    - name: Verify Plugin Deployment
      continue-on-error: true
      run: |
        echo "Listing registered plugins..."
        pac plugin list --environment https://org7cfbe420.crm.dynamics.com